In [1]:
import numpy as np

In [2]:
g = np.empty(9,dtype=np.uint8)
g[0:7] = 1
print(g)
k = g[0:7]
g[1:8] = k
g[0] = 0
g

[1 1 1 1 1 1 1 0 0]


array([0, 1, 1, 1, 1, 1, 1, 1, 0], dtype=uint8)

In [3]:
def shift(g):
    k = np.array(g,dtype=np.uint8)
    k[0] = g[1]
    k[1] = g[2]
    k[2] = g[3]
    k[3] = g[4]
    k[4] = g[5]
    k[5] = g[6]
    k[6] = g[7]
    k[7] = g[8]
    return k

In [4]:
def scrambler(seed,inputbits):
    g = np.empty(9,dtype=np.uint8)
    ipbits = np.array(inputbits,dtype=np.uint8)
    output = np.empty(len(inputbits),dtype=np.uint8)
    G = np.empty(len(inputbits),dtype=np.uint8)
    g[0:8] = seed
    for i in range(len(inputbits)):
        A = g[0] ^ g[1]
        B = A ^ g[2]
        C = B ^ g[3]
        D = C ^ g[4]
        g[8] = D ^ g[6]
        output[i] = g[0] ^ ipbits[i]
        G[i] = g[0]
        g[0:8] = g[1:9]
    return output,G  

In [5]:
g = [1,1,1,1,1,1,1,1]
g = np.array(g)
k,G = scrambler(g,[1,1,1,0,0,0,1,0,1,0,1,1,1,0])
ip,G = scrambler(g,k)
print(ip)

[1 1 1 0 0 0 1 0 1 0 1 1 1 0]


In [6]:
k

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0], dtype=uint8)

In [7]:
G

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0], dtype=uint8)

In [8]:
l = [1,2,3,4,5,6,7,8,9]
g = np.array(l)
print(shift(g))

[2 3 4 5 6 7 8 9 9]


In [9]:
g = [1,2,3,4,5,6,7,8]
g = np.array(g)
g[1:8] = g[0:7]
print(g)

[1 1 2 3 4 5 6 7]


In [10]:
class Scrambler:
    def __init__(self,seed,poly):
        self.seed = np.array(seed,dtype=np.uint8)
        self.poly = np.array(poly,dtype=np.uint8)
        self.g = np.empty(9,dtype=np.uint8)
        self.g[0:8] = self.seed
        self.x = np.empty
    
    def scramble(inputbit):
        pass

In [11]:
import numpy as np

In [12]:
# Testing modulo-2 operations with numpy polynomials
dividend = np.poly1d([1, 0, 0, 0, 0, 0, 0, 1])
print("Dividend:")
print(dividend)

divisor = np.poly1d([1, 1, 1, 0, 1])
print("Divisor:")
print(divisor)

quotient = np.mod(np.polydiv(dividend, divisor)[0], 2)
print(quotient)

Dividend:
   7
1 x + 1
Divisor:
   4     3     2
1 x + 1 x + 1 x + 1
[1. 1. 0. 1.]


In [13]:
def bits_to_poly(bits):
    return np.poly1d(bits)

def generate_x_n_k(n, k):
    poly_bits = np.array([1])
    poly_bits = np.pad(poly_bits, [(0, n - k)], mode = 'constant', constant_values = 0)
    return bits_to_poly(poly_bits)

def add_filler_bit(poly, filler = 1):
    filled_bits = np.array(poly)
    filled_bits = np.pad(filled_bits, [(1, 0)], mode = 'constant', constant_values = 1)
    return bits_to_poly(filled_bits)

In [14]:
bits = [1, 1, 1]
n = 7
k = 3

message_poly = bits_to_poly(bits)
print(f"Message polynomial:\n{message_poly}")

x_n_k = generate_x_n_k(n, k)
print(f"x^(n-k):\n{x_n_k}")

message_shifted = np.polymul(x_n_k, message_poly)
print(f"Shifted message polynomial:\n{message_shifted}")

Message polynomial:
   2
1 x + 1 x + 1
x^(n-k):
   4
1 x
Shifted message polynomial:
   6     5     4
1 x + 1 x + 1 x


In [15]:
# generator_poly = np.poly1d([1, 1, 0, 0, 0, 1, 0, 1])  # g(x) from paper
generator_poly = np.poly1d([1, 1, 1, 0, 1])
print(f"Generator polynomial:\n{generator_poly}")

parity_poly = np.polydiv(message_shifted, generator_poly)[1]  # [1] indexes the remainder
parity_poly = bits_to_poly(np.mod(parity_poly, 2))
print(f"Parity polynomial:\n{parity_poly}")

Generator polynomial:
   4     3     2
1 x + 1 x + 1 x + 1
Parity polynomial:
   2
1 x


In [16]:
code_poly = np.polyadd(parity_poly, message_shifted)
code_poly = bits_to_poly(np.mod(code_poly, 2))
print(f"Codeword polynomial:\n{code_poly}")

packet_poly = add_filler_bit(code_poly, 1)
print(f"Packet polynomial:\n{packet_poly}")

print(f"Final encoded bits to be transmitted (leftmost bit is MSB):\n{np.array(packet_poly)}")

Codeword polynomial:
   6     5     4     2
1 x + 1 x + 1 x + 1 x
Packet polynomial:
   7     6     5     4     2
1 x + 1 x + 1 x + 1 x + 1 x
Final encoded bits to be transmitted (leftmost bit is MSB):
[1. 1. 1. 1. 0. 1. 0. 0.]
