In [3]:
import numpy as np

In [33]:
g = np.empty(9,dtype=np.uint8)
g[0:7] = 1
print(g)
k = g[0:7]
g[1:8] = k
g[0] = 0
g

[1 1 1 1 1 1 1 0 0]


array([0, 1, 1, 1, 1, 1, 1, 1, 0], dtype=uint8)

In [57]:
def shift(g):
    k = np.array(g,dtype=np.uint8)
    k[0] = g[1]
    k[1] = g[2]
    k[2] = g[3]
    k[3] = g[4]
    k[4] = g[5]
    k[5] = g[6]
    k[6] = g[7]
    k[7] = g[8]
    return k

In [14]:
def scrambler(seed,inputbits):
    g = np.empty(9,dtype=np.uint8)
    ipbits = np.array(inputbits,dtype=np.uint8)
    output = np.empty(len(inputbits),dtype=np.uint8)
    G = np.empty(len(inputbits),dtype=np.uint8)
    g[0:8] = seed
    for i in range(len(inputbits)):
        A = g[0] ^ g[1]
        B = A ^ g[2]
        C = B ^ g[3]
        D = C ^ g[4]
        g[8] = D ^ g[6]
        output[i] = g[0] ^ ipbits[i]
        G[i] = g[0]
        g[0:8] = g[1:9]
    return output,G  

In [18]:
g = [1,1,1,1,1,1,1,1]
g = np.array(g)
k,G = scrambler(g,[1,1,1,0,0,0,1,0,1,0,1,1,1,0])
ip,G = scrambler(g,k)
print(ip)

[1 1 1 0 0 0 1 0 1 0 1 1 1 0]


In [19]:
k

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0], dtype=uint8)

In [20]:
G

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0], dtype=uint8)

In [48]:
l = [1,2,3,4,5,6,7,8,9]
g = np.array(l)
print(shift(g))

[2 3 4 5 6 6 8 9 9]


In [4]:
g = [1,2,3,4,5,6,7,8]
g = np.array(g)
g[1:8] = g[0:7]
print(g)

[1 1 2 3 4 5 6 7]


In [ ]:
class Scrambler:
    def __init__(self,seed,poly):
        self.seed = np.array(seed,dtype=np.uint8)
        self.poly = np.array(poly,dtype=np.uint8)
        self.g = np.empty(9,dtype=np.uint8)
        self.g[0:8] = self.seed
        self.x = np.empty
    
    def scramble(inputbit):
        
    
    
    
    