In [1]:
import numpy as np

In [2]:
g = np.empty(9,dtype=np.uint8)
g[0:7] = 1
print(g)
k = g[0:7]
g[1:8] = k
g[0] = 0
g

[1 1 1 1 1 1 1 0 0]


array([0, 1, 1, 1, 1, 1, 1, 1, 0], dtype=uint8)

In [3]:
def shift(g):
    k = np.array(g,dtype=np.uint8)
    k[0] = g[1]
    k[1] = g[2]
    k[2] = g[3]
    k[3] = g[4]
    k[4] = g[5]
    k[5] = g[6]
    k[6] = g[7]
    k[7] = g[8]
    return k

In [4]:
def scrambler(seed,inputbits):
    g = np.empty(9,dtype=np.uint8)
    ipbits = np.array(inputbits,dtype=np.uint8)
    output = np.empty(len(inputbits),dtype=np.uint8)
    G = np.empty(len(inputbits),dtype=np.uint8)
    g[0:8] = seed
    for i in range(len(inputbits)):
        A = g[0] ^ g[1]
        B = A ^ g[2]
        C = B ^ g[3]
        D = C ^ g[4]
        g[8] = D ^ g[6]
        output[i] = g[0] ^ ipbits[i]
        G[i] = g[0]
        g[0:8] = g[1:9]
    return output,G  

In [5]:
g = [1,1,1,1,1,1,1,1]
g = np.array(g)
k,G = scrambler(g,[1,1,1,0,0,0,1,0,1,0,1,1,1,0])
ip,G = scrambler(g,k)
print(ip)

[1 1 1 0 0 0 1 0 1 0 1 1 1 0]


In [6]:
k

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0], dtype=uint8)

In [7]:
G

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0], dtype=uint8)

In [8]:
l = [1,2,3,4,5,6,7,8,9]
g = np.array(l)
print(shift(g))

[2 3 4 5 6 7 8 9 9]


In [9]:
g = [1,2,3,4,5,6,7,8]
g = np.array(g)
g[1:8] = g[0:7]
print(g)

[1 1 2 3 4 5 6 7]


In [10]:
class Scrambler:
    def __init__(self,seed,poly):
        self.seed = np.array(seed,dtype=np.uint8)
        self.poly = np.array(poly,dtype=np.uint8)
        self.g = np.empty(9,dtype=np.uint8)
        self.g[0:8] = self.seed
        self.x = np.empty
    
    def scramble(inputbit):
        pass

In [11]:
# Testing modulo-2 operations with numpy polynomials
dividend = np.poly1d([1, 0, 0, 0, 0, 0, 0, 1])
print("Dividend:")
print(dividend)

divisor = np.poly1d([1, 1, 1, 0, 1])
print("Divisor:")
print(divisor)

quotient = np.mod(np.polydiv(dividend, divisor)[0], 2)
print(quotient)

Dividend:
   7
1 x + 1
Divisor:
   4     3     2
1 x + 1 x + 1 x + 1
[1. 1. 0. 1.]


## The complete procedure begins here.

In [12]:
import numpy as np

In [13]:
def scrambler(seed, inputbits):
    g = np.empty(9, dtype = np.uint8)
    ipbits = np.array(inputbits, dtype = np.uint8)
    output = np.empty(len(inputbits), dtype = np.uint8)
    G = np.empty(len(inputbits), dtype = np.uint8)
    g[0:8] = seed
    for i in range(len(inputbits)):
        A = g[0] ^ g[1]
        B = A ^ g[2]
        C = B ^ g[3]
        D = C ^ g[4]
        g[8] = D ^ g[6]
        output[i] = g[0] ^ ipbits[i]
        G[i] = g[0]
        g[0:8] = g[1:9]
    return output, G

def bits_to_poly(bits):
    return np.poly1d(bits)

def generate_x_power_n(n):
    poly_bits = np.array([1])
    poly_bits = np.pad(poly_bits, [(0, n)], mode = 'constant', constant_values = 0)
    return bits_to_poly(poly_bits)

def make_64_bits(arr, n):
    filled_bits = arr
    to_fill = np.zeros((1, n - len(arr) + 1))  # extra 0 is to compensate for the filler bit at 64th index
    filled_bits = np.append(to_fill, filled_bits)
    return filled_bits

def packeting(bch):
    head = np.array([1,1,1,0,1,0,1,1,1,0,0,1,0,0,0,0])
    tail = np.array([1,1,0,0,0,1,0,1, 1,1,0,0,0,1,0,1, 1,1,0,0,0,1,0,1, 1,1,0,0,0,1,0,1, 
                     1,1,0,0,0,1,0,1, 1,1,0,0,0,1,0,1, 1,1,0,0,0,1,0,1, 0,1,1,1,1,0,0,1])
    packet1 = np.append(head,bch)
    packet2 = np.append(packet1,tail)
    return packet2

In [14]:
input = np.array([1,1,1,1,1,1,1,1,1,1])
lenin = len(input)
print(lenin)
extra = 56-(lenin%56)
print(extra)

10
46


In [15]:
fillarray = np.array([0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
                      0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0])
print(len(fillarray))
filler = fillarray[0:extra]
print(len(filler))
input = np.append(input, filler)
print(len(input))

55
46
56


In [16]:
message_bits = input

g = [1,1,1,1,1,1,1,1]
g = np.array(g)

scrambled_data, G = scrambler(g, message_bits)
descrambled_data, G = scrambler(g, scrambled_data)
print(scrambled_data)

[0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1
 1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 0 1 1]


In [17]:
bits = np.flip(scrambled_data)

n = 63
k = 56

message_poly = bits_to_poly(bits)
print(f"Message polynomial:\n{message_poly}")

x_n_k = generate_x_power_n(n - k)
print(f"x^(n-k):\n{x_n_k}")

# message_shifted = np.polymul(x_n_k, message_poly)
# print(f"Shifted message polynomial:\n{message_shifted}")

Message polynomial:
   55     54     51     49     45     44     43     42     40     39
1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x 
      37     36     35     34     31     30     29     28     23     22
 + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x 
      20     17     16     13     12     10     9     8
 + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x + 1 x
x^(n-k):
   7
1 x


In [18]:
generator_poly = np.poly1d([1, 1, 0, 0, 0, 1, 0, 1])  # g(x) from paper
print(f"Generator polynomial:\n{generator_poly}")

parity_poly = np.polydiv(message_poly, generator_poly)[1]  # [1] indexes the remainder
parity_poly = bits_to_poly(np.mod(parity_poly, 2))
print(f"Parity polynomial:\n{parity_poly}")

Generator polynomial:
   7     6     2
1 x + 1 x + 1 x + 1
Parity polynomial:
   6     5     4
1 x + 1 x + 1 x + 1 x


In [19]:
parity_shifted = np.polymul(generate_x_power_n(k), parity_poly)
print(f"Shifted parity polynomial:\n{parity_shifted}")

Shifted parity polynomial:
   62     61     60     57
1 x  + 1 x  + 1 x  + 1 x 


In [20]:
code_poly = np.polyadd(parity_shifted, message_poly)
code_poly = bits_to_poly(np.mod(code_poly, 2))
print(f"Codeword polynomial:\n{code_poly}")

encoded_bits = make_64_bits(np.array(code_poly), n)

print(f"Final encoded bits to be transmitted (leftmost bit is MSB):\n{encoded_bits}")

Codeword polynomial:
   62     61     60     57     55     54     51     49     45     44
1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x 
      43     42     40     39     37     36     35     34     31     30
 + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x 
      29     28     23     22     20     17     16     13     12     10
 + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x  + 1 x 
      9     8
 + 1 x + 1 x
Final encoded bits to be transmitted (leftmost bit is MSB):
[0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1.
 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
bch = np.flip(encoded_bits)
packet = packeting(bch)
print(packet)

[1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.
 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1.
 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1.
 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1.]
